import LoginBtn from './LoginBtn';
import './globals.css';
import Link from 'next/link';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import { cookies } from 'next/headers';
import DarkMode from './DarkMode';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);

  let res = cookies().get('mode');

  return (
    <html lang="en">
      <body
        className={res !== undefined && res.value === 'dark' ? 'dark-mode' : ''}
      >
        <div className="navbar">
          <Link href="/" className="logo">
            Appleforum
          </Link>
          <Link href="/list">List</Link>
          <LoginBtn session={session} />
          <DarkMode />
        </div>{' '}
        {children}
      </body>
    </html>
  );
}
